const PROJECT_ID = "worktimepro-d4f8c";
const SCOPE = "https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/firebase.messaging";
const enc = new TextEncoder();
function b64u(bytes){return btoa(String.fromCharCode(...bytes)).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}
function b64uText(s){return b64u(enc.encode(s))}
function pemBytes(pem){const s=pem.replace(/-----[^-]+-----/g,"").replace(/\s/g,"");return Uint8Array.from(atob(s),c=>c.charCodeAt(0))}
async function accessToken(env){
 const now=Math.floor(Date.now()/1000),head=b64uText(JSON.stringify({alg:"RS256",typ:"JWT"})),body=b64uText(JSON.stringify({iss:env.FIREBASE_CLIENT_EMAIL,scope:SCOPE,aud:"https://oauth2.googleapis.com/token",iat:now,exp:now+3600}));
 const key=await crypto.subtle.importKey("pkcs8",pemBytes(env.FIREBASE_PRIVATE_KEY.replace(/\\n/g,"\n")),{name:"RSASSA-PKCS1-v1_5",hash:"SHA-256"},false,["sign"]);
 const sig=await crypto.subtle.sign("RSASSA-PKCS1-v1_5",key,enc.encode(`${head}.${body}`));
 const jwt=`${head}.${body}.${b64u(new Uint8Array(sig))}`;
 const r=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"urn:ietf:params:oauth:grant-type:jwt-bearer",assertion:jwt})});
 if(!r.ok)throw new Error("OAuth "+await r.text());return (await r.json()).access_token;
}
function fv(v){if(!v)return null;if("stringValue" in v)return v.stringValue;if("integerValue" in v)return Number(v.integerValue);if("booleanValue" in v)return v.booleanValue;if("arrayValue" in v)return (v.arrayValue.values||[]).map(fv);if("mapValue" in v){const o={};for(const [k,x] of Object.entries(v.mapValue.fields||{}))o[k]=fv(x);return o}return null}
function field(v){if(Array.isArray(v))return {arrayValue:{values:v.map(field)}};if(v&&typeof v==="object"){const fields={};for(const [k,x] of Object.entries(v))fields[k]=field(x);return {mapValue:{fields}}}if(typeof v==="boolean")return {booleanValue:v};if(typeof v==="number")return {integerValue:String(v)};return {stringValue:String(v??"")}}
function docObj(d){const o={id:d.name.split("/").pop()};for(const [k,v] of Object.entries(d.fields||{}))o[k]=fv(v);return o}
async function getJson(url,token){const r=await fetch(url,{headers:{authorization:`Bearer ${token}`}});if(!r.ok)throw new Error(await r.text());return r.json()}
async function patchTask(id,updates,token){const fields={};for(const [k,v] of Object.entries(updates))fields[k]=field(v);const masks=Object.keys(fields).map(k=>"updateMask.fieldPaths="+encodeURIComponent(k)).join("&");const u=`https://firestore.googleapis.com/v1/projects/${PROJECT_ID}/databases/(default)/documents/tasks/${id}?${masks}`;const r=await fetch(u,{method:"PATCH",headers:{authorization:`Bearer ${token}`,"content-type":"application/json"},body:JSON.stringify({fields})});if(!r.ok)throw new Error(await r.text())}
async function userToken(uid,token){try{const d=await getJson(`https://firestore.googleapis.com/v1/projects/${PROJECT_ID}/databases/(default)/documents/users/${uid}`,token);return fv(d.fields?.fcmToken)||""}catch{return ""}}
async function sendFCM(device,task,token){const body={message:{token:device,data:{title:`${task.priority==="Urgent"?"URGENT • ":""}${task.title}`,body:task.description||`Task at ${task.time}`,taskId:task.id,url:"./"},webpush:{headers:{Urgency:task.priority==="Urgent"?"high":"normal"}}}};const r=await fetch(`https://fcm.googleapis.com/v1/projects/${PROJECT_ID}/messages:send`,{method:"POST",headers:{authorization:`Bearer ${token}`,"content-type":"application/json"},body:JSON.stringify(body)});return r.ok}
function nextDue(task){const d=new Date(task.nextNotifyAt);if(task.repeat==="daily")return new Date(d.getTime()+86400000).toISOString();if(task.repeat==="selected"){const days=(task.selectedDays||[]).map(Number);for(let i=1;i<=7;i++){const n=new Date(d.getTime()+i*86400000);const local=new Date(n.getTime()+330*60000);if(days.includes(local.getUTCDay()))return n.toISOString()}}return null}
async function run(env){const token=await accessToken(env),url=`https://firestore.googleapis.com/v1/projects/${PROJECT_ID}/databases/(default)/documents/tasks?pageSize=200`;const data=await getJson(url,token),now=Date.now();let sent=0;for(const raw of data.documents||[]){const t=docObj(raw);if(!t.nextNotifyAt||Date.parse(t.nextNotifyAt)>now+65000)continue;if(t.repeat==="once"&&t.notificationState==="sent")continue;for(const uid of t.assignedTo||[]){const device=await userToken(uid,token);if(device&&await sendFCM(device,t,token))sent++}const next=nextDue(t);await patchTask(t.id,next?{nextNotifyAt:next,lastNotifiedAt:new Date().toISOString(),notificationState:"pending"}:{lastNotifiedAt:new Date().toISOString(),notificationState:"sent"},token)}return sent}
export default {async scheduled(c,env,ctx){ctx.waitUntil(run(env))},async fetch(req,env){const u=new URL(req.url);if(u.pathname!=="/health")return new Response("WorkTime Pro notification scheduler");try{return Response.json({ok:true,sent:await run(env)})}catch(e){return Response.json({ok:false,error:String(e)},{status:500})}}};
